version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "8089:8089"
    entrypoint: bash -c 'curl https://raw.githubusercontent.com/chameleonhead/trsys/loadtesting/locustfile.py -o locustfile.py && locust --master'
  
  worker1:
    image: locustio/locust
    entrypoint: bash -c 'curl https://raw.githubusercontent.com/chameleonhead/trsys/loadtesting/locustfile.py -o locustfile.py && locust --worker --master-host master'

  worker2:
    image: locustio/locust
    entrypoint: bash -c 'curl https://raw.githubusercontent.com/chameleonhead/trsys/loadtesting/locustfile.py -o locustfile.py && locust --worker --master-host master'
