version: '3.5'

services:
  nginx:
    depends_on:
      - server
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  server:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes: 
      - .:/app
    working_dir: /app
    command: dotnet run --project ./src/Trsys.Web/Trsys.Web.csproj
  loadtest:
    depends_on:
      - nginx
    image: mcr.microsoft.com/dotnet/sdk:5.0
    volumes: 
      - .:/app
    working_dir: /app
    command: bash -c "sleep 10 && dotnet run --project ./tests/LoadTesting/LoadTesting.csproj"
