version: "3.5"

services:
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    volumes:
      - ./docker/azurite/data:/data
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/ssl-cert:/etc/nginx/ssl-cert
      - ./docker/nginx/create_ssl.sh:/docker-entrypoint.d/create_ssl.sh
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 443:443
      - 80:80
      # - 8080:80
      # - 8443:443
    depends_on:
      - app1
      - app2
  app1:
    build:
      context: ./docker/app
    working_dir: /app
    command: bash -c "rsync --recursive --delete --exclude-from=/app/.copyignore /workspace/ /app/ && dotnet run --project src/Trsys.Web/Trsys.Web.csproj"
    volumes:
      - ./docker/app/workdir1:/app
      - ./docker/app/.copyignore:/app/.copyignore
      - .:/workspace
    environment:
      - ConnectionStrings__DefaultConnection=Persist Security Info=False;User ID=sa;Password=P@ssw0rd;Initial Catalog=TrsysDatabase;Server=db
      - ConnectionStrings__RedisConnection=redis
      - ConnectionStrings__BlobStorageConnection=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storage:10000/devstoreaccount1;QueueEndpoint=http://storage:10001/devstoreaccount1;
      - Trsys.Web__DataContainerName=data
    depends_on:
      - db
      - storage
      - redis
  app2:
    build:
      context: ./docker/app
    working_dir: /app
    command: bash -c "rsync --recursive --delete --exclude-from=/app/.copyignore /workspace/ /app/ && dotnet run --project src/Trsys.Web/Trsys.Web.csproj"
    volumes:
      - ./docker/app/workdir2:/app
      - ./docker/app/.copyignore:/app/.copyignore
      - .:/workspace
    environment:
      - ConnectionStrings__DefaultConnection=Persist Security Info=False;User ID=sa;Password=P@ssw0rd;Initial Catalog=TrsysDatabase;Server=db
      - ConnectionStrings__RedisConnection=redis
      - ConnectionStrings__BlobStorageConnection=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://storage:10000/devstoreaccount1;QueueEndpoint=http://storage:10001/devstoreaccount1;
      - Trsys.Web__DataContainerName=data
    depends_on:
      - db
      - storage
      - redis
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    volumes:
      - ./docker/sqlserver/data:/var/opt/mssql/data
      - ./docker/sqlserver/log:/var/opt/mssql/log
      - ./docker/sqlserver/secrets:/var/opt/mssql/secrets
    ports:
      - 1433:1433
  redis:
    image: redis
    ports:
      - 6379:6379
