version: "3.7"

services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/ssl-cert:/etc/nginx/ssl-cert
      - ./docker/nginx/create_ssl.sh:/docker-entrypoint.d/create_ssl.sh
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - app
  app:
    build:
      context: ./docker/app
    command: bash -c "dotnet run --project src/Trsys.Web/Trsys.Web.csproj"
    working_dir: /workspace
    volumes:
      - .:/workspace
    environment:
      - ConnectionStrings__DefaultConnection=Persist Security Info=False;User ID=sa;Password=P@ssw0rd;Initial Catalog=TrsysDatabase;Server=db;Trust Server Certificate=True
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    volumes:
      - ./docker/sqlserver/data:/var/opt/mssql/data
      - ./docker/sqlserver/log:/var/opt/mssql/log
      - ./docker/sqlserver/secrets:/var/opt/mssql/secrets
    ports:
      - 1433:1433
  smtp:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    